name: CI (PHP)

on:
  push:
    paths-ignore:
      - '.github/workflows/ci-ts.yml'
      - 'neojs/**'
  pull_request:
    paths-ignore:
      - '.github/workflows/ci-ts.yml'
      - 'neojs/**'

jobs:
  PHPUnit:
    name: "PHPUnit with PHP ${{ matrix.php }}"

    strategy:
      matrix:
        include:
          - php: '8.3'

    runs-on: ubuntu-latest

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, intl
          tools: composer

      - name: Checkout
        uses: actions/checkout@v4

      - run: composer install
      - run: vendor/bin/phpunit

  PHPCS:
    name: "PHPCS with PHP ${{ matrix.php }}"

    strategy:
      matrix:
        include:
          - php: '8.3'

    runs-on: ubuntu-latest

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, intl
          tools: composer

      - name: Checkout
        uses: actions/checkout@v4

      - run: composer install
      - run: vendor/bin/phpcs -p -s --standard=phpcs.xml

  PHPStan:
    name: "PHPStan with PHP ${{ matrix.php }}"

    strategy:
      matrix:
        include:
          - php: '8.3'

    runs-on: ubuntu-latest

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, intl
          tools: composer

      - name: Checkout
        uses: actions/checkout@v4

      - run: composer install
      - run: vendor/bin/phpstan analyze --configuration=phpstan.neon --memory-limit=2G

  Psalm:
    name: "Psalm with PHP ${{ matrix.php }}"

    continue-on-error: true # TODO

    strategy:
      matrix:
        include:
          - php: '8.3'

    runs-on: ubuntu-latest

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, intl
          tools: composer

      - name: Checkout
        uses: actions/checkout@v4

      - run: composer install
      - run: vendor/bin/psalm --config=psalm.xml --no-diff
