name: CI (TypeScript)

on:
  push:
    paths:
      - '.github/workflows/ci-ts.yml'
      - 'neojs/**'
  pull_request:
    paths:
      - '.github/workflows/ci-ts.yml'
      - 'neojs/**'

jobs:
  build:
    name: "NeoJS build"

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./neojs

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Upload dist folder
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: neojs/dist

  test:
    name: "NeoJS tests"

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./neojs

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Test
        run: npm run test

  lint:
    name: "NeoJS linting"

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./neojs

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Lint
        run: npm run lint

  commit-dist:
    name: "Commit dist folder"
    needs: [build, test, lint]
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download dist folder
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: neojs/dist

      - name: Commit dist folder
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -f neojs/dist
          git commit -m "Update dist folder" -a || echo "No changes to commit"
          git push
