services:
  mediawiki:
    image: ghcr.io/professionalwiki/neowiki:latest
    restart: unless-stopped
    ports:
      - "${MW_SERVER_PORT:-8484}:80"
    volumes:
      - mediawiki-images-data:/var/www/html/w/images
      # Uncomment to use custom LocalSettings.
      # - ./LocalSettings.php:/var/www/html/w/LocalSettings.php:ro
    depends_on:
      - db
      - neo
    environment:
      - MARIADB_DATABASE
      - MARIADB_USER
      - MARIADB_PASSWORD
      - MW_SERVER
      - NEO4J_URL_EXTERNAL
      - NEO4J_USERNAME
      - NEO4J_PASSWORD
      - NEO4J_USERNAME_READ
      - NEO4J_PASSWORD_READ
    healthcheck:
      test: "curl -fsSL http://localhost:80/index.php/Special:Version | grep 'Jeroen De Dauw'"
      interval: 60s
      timeout: 5s
      retries: 1

  db:
    image: mariadb:11.8
    restart: unless-stopped
    volumes:
      - mediawiki-db-data:/var/lib/mysql
    environment:
      - MARIADB_ROOT_PASSWORD
      - MARIADB_DATABASE
      - MARIADB_USER
      - MARIADB_PASSWORD
    healthcheck:
      test: ["CMD", "mariadb-admin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 10s
      retries: 4

  neo:
    image: neo4j:enterprise
    restart: unless-stopped
    volumes:
      - neo4j-data:/data
    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=eval
      - NEO4J_AUTH
    healthcheck:
      test: "wget http://localhost:7474/browser -O - | grep 'Neo4j Browser'"
      interval: 5s
      timeout: 1s
      retries: 10

  caddy:
    image: caddy:2.10-alpine
    restart: unless-stopped
    profiles:
      - production
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy-data:/data
      - caddy-config:/config
    environment:
      - MW_SERVER
    depends_on:
      - mediawiki

volumes:
  mediawiki-db-data:
  mediawiki-images-data:
  neo4j-data:
  caddy-data:
  caddy-config:
