version: '3.8'

services:
  php:
    build: .
#    depends_on:
#      - graph
    volumes:
      - ./:/app
    working_dir: /app

  graph:
    image: neo4j
    restart: unless-stopped
    ports:
      - "127.0.0.1:7474:7474"
      - "127.0.0.1:7687:7687"
    volumes:
      - neo4j-data:/data
    environment:
      - NEO4J_AUTH=neo4j/neo4j

  node:
    image: node:20-alpine
    user: "node"
    working_dir: /home/node/app
    volumes:
      - ./neojs:/home/node/app

volumes:
  neo4j-data:
